<script setup lang="ts">
import { ref } from 'vue';
import Section from '@/components/common/Section.vue';
import SirCard from '~/components/common/SirCard.vue';
import Connect from '~/components/wallet/Connect.vue';
import SirProgressBar from '~/components/common/SirProgressBar.vue';
import { useWallet } from '~/composables/useWallet';
import { useNfts } from "~/composables/useNfts";

const { isConnected, address } = useWallet();
const nfts = useNfts();
const saleStore = useSaleStore();

let bt: Ref<Array<number>> = ref([]);
let mj: Ref<Array<number>> = ref([]);

// Fetch NFTs if connected
watch(isConnected, async (newVal) => {
  if (newVal) {
    bt.value = await nfts.fetchWalletButerinCards(address.value as string) as Array<number>
    mj.value = await nfts.fetchWalletMinedJpeg(address.value as string) as Array<number>
  }
})
const bullets = [
  {
    i: 1,
    text: 'We are conducting multiple private protocol <span class="font-semibold text-redAccent">code audits with different security firms</span> and plan a public audit as well. After identifying and fixing any important bugs, we will proceed with the <span class="font-semibold text-redAccent">mainnet relaunch</span>.'
  },
  {
    i: 2,
    text: 'During the initial three-year period, <span class="font-semibold text-redAccent">tokens will unlock linearly</span>. After this phase, all newly issued tokens will be allocated exclusively to liquidity providers.',
  },
  {
    i: 3,
    text: 'As a <span class="font-semibold text-redAccent">revenue-sharing token</span>, SIR entitles stakers to a percentage of the fees generated by the protocol, converted and <span class="font-semibold text-redAccent">paid out in ETH</span>. For a more detailed explanation, please refer to <a href="https://docs.sir.trading/" target="_blank" class="underline">our documentation</a>.'
  }
];

const chartLegend = [
  { label: "Liquidity providers", color: "bg-[#CC9901]" },
  { label: "Team & Contributors", color: "bg-[#6A3C99]" },
  { label: "Presale", color: "bg-[#44AA99]" },
  { label: "Public sale", color: "bg-[#882255]" },
  { label: "Treasury", color: "bg-[#CC6677]" },
  { label: "Compensation fund (victims of the hack)", color: "bg-[#117733]" },
]

definePageMeta({
  middleware: ['geoblock']
})

</script>

<template>
  <UContainer>

    <Section variant="background">
      <template #header>Your Allocation</template>
      <Allocations />
    </Section>

    <Section variant="background">
      <template #header>SIR Token Presale</template>
      <div class="flex flex-col section-text-block mt-0 mb-6">
        <p>
          The presale is over.
          Despite the recent <a href="https://x.com/DecurityHQ/status/1906270316935942350" target="_blank"
            class="underline">exploit of the SIR protocol</a>, we plan on relaunching very soon. <span
            class="font-semibold text-redAccent">Your original SIR token allocation remains valid </span>and will carry
          over.
        </p>
        <!-- <p>
          We <span class="font-semibold text-redAccent">plan on raising additional funds</span> at a slightly higher valuation. We are undergoing multiple private audits
          and plan on doing a public audit as well to squash any left bugs.
        </p>
        <p>
          If the audits are successful, the protocol will <span class="font-semibold text-redAccent">launch on Ethereum mainnet</span>,
          a 2nd time.
        </p> -->
      </div>
      <!--      <div class="flex flex-col md:flex-row md:justify-evenly w-full mb-3">-->
      <!--        <SirProgressBar/>-->
      <!--      </div>-->
      <div class="flex flex-col md:flex-row items-center md:justify-end w-full">
        <Connect />
      </div>
    </Section>

    <Section variant="background" v-if="isConnected">
      <template #header>Your Contributions</template>
      <div class="flex flex-col section-text-block mt-0 mb-6">
        <p>
          This reflects your allocation of SIR tokens based on your original presale participation and number of locked
          NFTs.
        </p>
        <p>
          <span class="font-semibold text-redAccent">Please note:</span> any tokens sold during the pre-exploit live
          version
          of SIR will be deducted from your allocation.
        </p>
        <PresaleNftList />
      </div>
    </Section>

    <Section variant="background">
      <template #header>Next Steps</template>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full">
        <SirCard size="xs" v-for="bullet in bullets" :key="bullet.i">
          <template #header>
            <div class="rounded-xl font-black text-rob-roy-300 ring-2 ring-rob-roy-300 text-center py-3 px-4">
              {{ bullet.i }}
            </div>
          </template>
          <p class="p-3 text-left" v-html="bullet.text"></p>
        </SirCard>
      </div>
      <div class="flex flex-col md:flex-row md:justify-evenly items-center w-full p-6 gap-12 md:gap-0 ">
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>for the first three years</span>
          </p>
          <picture>
            <img alt="Emissions for the first 3 years" src="/presale_first_three_years.png"
              class="block mx-auto h-[345px] w-auto object-contain" />
          </picture>
        </div>
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>after three years</span>
          </p>
          <picture>
            <img alt="Emissions after the 3rd year" src="/sale_after_three_years.png"
              class="block mx-auto h-[345px] w-auto object-contain" />
          </picture>
        </div>
      </div>
      <div class="flex flex-row flex-wrap justify-center items-center w-full p-6 gap-6 ">
        <div v-for="item in chartLegend" :key="item.label" class="flex flex-inline items-center gap-1">
          <div :class="['w-[1rem] h-[1rem] rounded-full', ` ${item.color}`]" />
          {{ item.label }}
        </div>
      </div>
    </Section>
    <footer class="footer">
      <div>
        <ULink to="/sale_disclaimer">Sale discaimer</ULink>
      </div>
    </footer>
  </UContainer>
</template>

<style scoped>
h6 {
  @apply text-gray-400;
}

.paragraphs p {
  margin-bottom: 1rem;
}

footer {
  @apply flex flex-col items-center justify-center w-full py-10;
}
</style>
