<script setup lang="ts">
import { ref, computed } from 'vue';
import Section from '@/components/common/Section.vue';
import SirCard from '~/components/common/SirCard.vue';
import Connect from '~/components/wallet/Connect.vue';
import { useWallet } from '~/composables/useWallet';
import SirHero from '~/components/common/SirHero.vue';
import SirProgressBar from '~/components/common/SirProgressBar.vue';

import SirButton from "~/components/common/SirButton.vue";
import NftList from "~/components/fundraise/NftList.vue";
import PreviousContributions from "~/components/fundraise/PreviousContributions.vue";



const { isConnected, address, hasAgreed } = useWallet();
const bullets = [
  {
    i: 1,
    text: 'SIR, the native token of the SIR protocol, is issued at a constant rate of 2015 million SIR per year ad infinitum. Primarily, the tokens are allocated to Liquidity Providers (LPs) in selected vaults within the SIR protocol.'
  },
  {
    i: 2,
    text: 'During the initial three years, tokens will also be distributed to various groups, including 10% to funders. It is important to note that tokens cannot be claimed before they are issued.',
  },
  {
    i: 3,
    text: 'SIR is a revenue-sharing token. A small percentage of the fees generated by the protocol will be distributed to SIR stakers. For more details visit our docs.'
  }
];


</script>

<template>
  <UContainer>
    <SirHero image="hero_image_optimized.png">
      <template #title>
        Be part of making SIR a reality
      </template>
    </SirHero>
    <Section variant="background">
      <template #header>{{isConnected ? "Project Funding Progress" : "Contribute to the fundraiser"}}</template>
      <p class="section-text-block mb-3">
        Some text about what will happen when you contribute and perhaps mentioning buterin cards.
      </p>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full mb-3">
        <SirProgressBar />
      </div>
      <div class="flex flex-col md:flex-row items-center md:justify-end w-full">
        <Connect />
      </div>
    </Section>
    <Section variant="background" v-if="isConnected">
      <template #header>Contribute to the Fundraiser</template>
      <div class="flex flex-col gap-3 w-full">
        <PreviousContributions />
        <NftList />
      </div>
    </Section>
    <Section variant="background">
      <template #header>How it works</template>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full">
        <SirCard size="xs" v-for="bullet in bullets" :key="bullet.i">
          <template #header>
            <div class="rounded-xl font-black text-rob-roy-300 ring-2 ring-rob-roy-300 text-center py-3 px-4">
              {{ bullet.i }}
            </div>
          </template>
          <p class="p-3 text-left">{{ bullet.text }}</p>
        </SirCard>
      </div>
      <div class="flex flex-col md:flex-row md:justify-evenly items-center w-full p-6 gap-12 md:gap-0 ">
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>for the first three years</span>
          </p>
          <div class="flex justify-center">
            <NuxtImg src="first_years_emission.png" sizes="100vw md:300px" />
          </div>
        </div>
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>after three years</span>
          </p>
          <div class="flex justify-center">
            <NuxtImg src="3_years_emission.png" sizes="100vw md:300px" />
          </div>
        </div>
      </div>
    </Section>
    <Disclaimer v-if="!hasAgreed"/>
  </UContainer>
</template>

<style scoped>
h6 {
  @apply text-gray-400;
}

.paragraphs p {
  margin-bottom: 1rem;
}
</style>