<script setup lang="ts">
import Section from '@/components/common/Section.vue'
import SirCard from "~/components/common/SirCard.vue";
import Connect from "~/components/wallet/Connect.vue";
import {useWallet} from "~/composables/useWallet";

const {isConnected, hasAgreed, address} = useWallet();




const bullets = [
  {
    i: 1,
    text: 'SIR, the native token of the SIR protocol, is issued at a constant rate of 2015 million SIR per year ad infinitum. Primarily, the tokens are allocated to Liquidity Providers (LPs) in selected vaults within the SIR protocol.'
  }, {
    i: 2,
    text: 'During the initial three years, tokens will also be distributed to various groups, including 10% to funders. It is important to note that tokens cannot be claimed before they are issued.',

  }, {
    i: 3,
    text: 'SIR is a revenue-sharing token. A small percentage of the fees generated by the protocol will be distributed to SIR stakers. For more details visit our docs.'
  },
]
</script>
<template>
  <UContainer>
<!--    <SirHero image="logo_240x240.png">-->
<!--      <template #title>-->
<!--        Safer Leverage for-->
<!--        <span class="text-primary inline-flex">Long-term</span> Investors-->
<!--      </template>-->
<!--      <template #description>-->
<!--        Be part of the SIR protocol fundraising-->
<!--      </template>-->
<!--    </SirHero>-->
    <Section variant="background">
      <Connect />
      <div>
        <p>{{isConnected}}</p>
        <p>{{hasAgreed}}</p>
        <p>{{address}}</p>
      </div>
    </Section>
    <Disclaimer v-if="!hasAgreed"/>
    <Section class-name="px-0">
      <template v-slot:content>
        Be a part of making SIR reality. By being an early patreon you help covering development costs. In return you
        get SIR tokens that...
      </template>
      <UProgress class="my-6" size="5xl" :value="70"></UProgress>
      <div class="flex flex-row w-full justify-center">
        <UButton color="green" variant="solid" size="lg" class="w-1/3 text-center">
          <span class="text-white w-full">Contribute</span>
        </UButton>
      </div>
    </Section>

    <Section class-name="px-0">
      <div class="flex flex-col md:flex-row md:justify-evenly w-full">
        <SirCard size="xs" v-for="bullet in bullets" :key="bullet.i">
          <template #header>
            <UBadge color="gray" variant="solid" size="xl">{{bullet.i}}</UBadge>
          </template>
          <p>{{bullet.text}}</p>
        </SirCard>
      </div>
    </Section>

  </UContainer>
</template>

<style scoped>

h6 {
  @apply text-gray-400;
}

.paragraphs p {
  margin-bottom: 1rem;
}
</style>
