<script setup lang="ts">
import {ref} from 'vue';
import Section from '@/components/common/Section.vue';
import SirCard from '~/components/common/SirCard.vue';
import Connect from '~/components/wallet/Connect.vue';
import SirProgressBar from '~/components/common/SirProgressBar.vue';
import NftList from "~/components/sale/NftList.vue";
import PreviousContributions from "~/components/sale/PreviousContributions.vue";
import {useWallet} from '~/composables/useWallet';
import {useNfts} from "~/composables/useNfts";

const {isConnected, address, isChainCorrect} = useWallet();
const nfts = useNfts();

let bt: Ref<Array<number>> = ref([]);
let mj: Ref<Array<number>> = ref([]);

// Fetch NFTs if connected
watch(isConnected, async (newVal) => {
  if (newVal) {
    bt.value = await nfts.fetchWalletButerinCards(address.value as string) as Array<number>
    mj.value = await nfts.fetchWalletMinedJpeg(address.value as string) as Array<number>
  }
})
const bullets = [
  {
    i: 1,
    text: 'Following the token sale, we will conduct a comprehensive protocol <span class="font-semibold text-redAccent">code audit with <a href="https://Code4rena.com" target="_blank" class="underline">Code4rena</a></span>. Provided no critical bugs are identified, we will proceed with the <span class="font-semibold text-redAccent">mainnet launch</span>.'
  },
  {
    i: 2,
    text: 'In the initial three-year period, token distribution will be allocated to various groups, with <span class="font-semibold text-redAccent">10-13% reserved for sale participants</span>. After this period, all newly issued tokens will be directed towards liquidity providers.',
  },
  {
    i: 3,
    text: 'As a <span class="font-semibold text-redAccent">revenue-sharing token</span>, SIR entitles stakers to a percentage of the fees generated by the protocol, converted and <span class="font-semibold text-redAccent">paid out in ETH</span>. For a more detailed explanation, please refer to <a href="https://docs.sir.trading/" target="_blank" class="underline">our documentation</a>.'
  }
];

const chartLegend = [
  {label: "LPers", color: "bg-[#271F59]"},
  {label: "Sale", color: "bg-[#867ACC]"},
  {label: "Treasury", color: "bg-[#7360E6]"},
  {label: "Pre-launch contributors", color: "bg-[#4737A9]"},
]

onMounted(() => {
  useWalletStore().checkAgreed()
  if (isConnected.value) {

  }

})


</script>

<template>
  <UContainer>
    <Section variant="background">
      <template #header>SIR Token Sale</template>
      <p class="section-text-block mb-3">
        Some text about what will happen when you contribute and perhaps mentioning buterin cards.
      </p>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full mb-3">
        <SirProgressBar/>
      </div>
      <div class="flex flex-col md:flex-row items-center md:justify-end w-full">
        <Connect/>
      </div>
    </Section>
    <Section variant="background" v-if="isConnected">
      <template #header>Contribute to SIR's Sale</template>
      <div class="flex flex-col gap-3 w-full items-center">
        <p class="flex flex-col">
          <span>You can withdraw your contribution within 24h</span>
          <span> if you change your mind. After that it’s locked in.</span>
        </p>
        <NftList/>
      </div>
    </Section>
    <Section variant="background">
      <template #header>How it works</template>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full">
        <SirCard size="xs" v-for="bullet in bullets" :key="bullet.i">
          <template #header>
            <div class="rounded-xl font-black text-rob-roy-300 ring-2 ring-rob-roy-300 text-center py-3 px-4">
              {{ bullet.i }}
            </div>
          </template>
          <p class="p-3 text-left" v-html="bullet.text"></p>
        </SirCard>
      </div>
      <div class="flex flex-col md:flex-row md:justify-evenly items-center w-full p-6 gap-12 md:gap-0 ">
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>for the first three years</span>
          </p>
          <picture class="max-w-[345px]">
            <img alt="Emissions for the first 3 years" src="/first_years_emission.png" class="mix-w-[300px]"/>
          </picture>
        </div>
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>after three years</span>
          </p>
          <picture class="max-w-[345px]">
            <img alt="Emissions after the 3rd year" src="/3_years_emission.png" class="mix-w-[300px]"/>
          </picture>
        </div>
      </div>
      <div class="flex flex-row flex-wrap justify-center items-center w-full p-6 gap-6 ">
        <div v-for="item in chartLegend" :key="item.label" class="flex flex-inline items-center gap-1">
          <div :class="['w-[1rem] h-[1rem] rounded-full', ` ${item.color}`]"/>
          {{ item.label }}
        </div>
      </div>
    </Section>
    <footer class="footer">
      <div>
        <ULink to="/sale_disclaimer">Sale discaimer</ULink>
      </div>
    </footer>
  </UContainer>
</template>

<style scoped>
h6 {
  @apply text-gray-400;
}

.paragraphs p {
  margin-bottom: 1rem;
}

footer {
  @apply flex flex-col items-center justify-center w-full py-10 bg-black-russian-950;
}
</style>