<script setup lang="ts">
import Section from '@/components/common/Section.vue';
import SirCard from '~/components/common/SirCard.vue';
import Connect from '~/components/wallet/Connect.vue';
import SirProgressBar from '~/components/common/SirProgressBar.vue';
import {useWallet} from '~/composables/useWallet';
import {useNfts} from "~/composables/useNfts";

const wallet = useWallet();
const nfts = useNfts();
const saleStore = useSaleStore();
console.log("sale total contributions: ", saleStore.saleState.totalContributions)

const bullets = [
  {
    i: 1,
    text: 'Following the token sale, we will conduct a comprehensive protocol <span class="font-semibold text-redAccent">code audit with <a href="https://Code4rena.com" target="_blank" class="underline">Code4rena</a></span>. Provided no critical bugs are identified, we will proceed with the <span class="font-semibold text-redAccent">mainnet launch</span>.'
  },
  {
    i: 2,
    text: 'In the initial three-year period, token distribution will be allocated to various groups, with <span class="font-semibold text-redAccent">10-13% reserved for sale participants</span>. After this period, all newly issued tokens will be directed towards liquidity providers.',
  },
  {
    i: 3,
    text: 'As a <span class="font-semibold text-redAccent">revenue-sharing token</span>, SIR entitles stakers to a percentage of the fees generated by the protocol, converted and <span class="font-semibold text-redAccent">paid out in ETH</span>. For a more detailed explanation, please refer to <a href="https://docs.sir.trading/" target="_blank" class="underline">our documentation</a>.'
  }
];

const chartLegend = [
  {label: "LPers", color: "bg-[#271F59]"},
  {label: "Sale", color: "bg-[#867ACC]"},
  {label: "Treasury", color: "bg-[#7360E6]"},
  {label: "Pre-launch contributors", color: "bg-[#4737A9]"},
]

definePageMeta({
  middleware: ['geoblock']
})

</script>

<template>
  <UContainer>
    <Section variant="background">
      <template #header>SIR Token Sale</template>
      <div class="flex flex-col section-text-block mt-0 mb-6">
        <p>
          <span class="font-semibold text-redAccent">The sale is over.</span> The funds raised will be used to perform audits on the protocol and refine the app.
        </p>
        <p>
          If the audit is successful, the protocol will <span class="font-semibold text-redAccent">launch on Ethereum mainnet</span>,
          enabling you to earn tokens by providing liquidity or buying on secondary markets.
        </p>
      </div>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full mb-3">
        <SirProgressBar/>
      </div>
      <div class="flex flex-col md:flex-row items-center md:justify-end w-full">
        <Connect/>
      </div>
    </Section>

    <Section variant="background" v-if="wallet.isConnected">
      <template #header>Contribute</template>
      <div class="flex flex-col gap-3 w-full items-center">
        <div class="flex flex-col  md:flex-row gap-3 md:gap-6 w-full p-1 md:py-3 md:px-6">
          <div class="flex flex-col w-full gap-3 text-left">
            <p><span class="font-semibold text-redAccent">1. Select a Stablecoin:</span> Choose one of the supported stablecoins—USDT, USDC, or DAI—for your contribution.</p>
            <p><span class="font-semibold text-redAccent">2. Make Contributions:</span> You can make multiple contributions during the sale.</p>
          </div>
          <div class="flex flex-col w-full gap-3 text-left">
            <p><span class="font-semibold text-redAccent">3. Withdrawal Flexibility:</span> If you change your mind, you have the flexibility to withdraw your contributions within 24 hours.</p>
            <p><span class="font-semibold text-redAccent">4. Token Unlock Schedule:</span> SIR tokens will unlock gradually over a period of three years to avoid sudden dumps into the market.</p>
          </div>
        </div>
        <SaleContribute/>
      </div>
    </Section>
    <Section variant="background">
      <template #header>How it works</template>
      <div class="flex flex-col md:flex-row md:justify-evenly w-full">
        <SirCard size="xs" v-for="bullet in bullets" :key="bullet.i">
          <template #header>
            <div class="rounded-xl font-black text-rob-roy-300 ring-2 ring-rob-roy-300 text-center py-3 px-4">
              {{ bullet.i }}
            </div>
          </template>
          <p class="p-3 text-left" v-html="bullet.text"></p>
        </SirCard>
      </div>
      <div class="flex flex-col md:flex-row md:justify-evenly items-center w-full p-6 gap-12 md:gap-0 ">
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>for the first three years</span>
          </p>
          <picture class="max-w-[345px]">
            <img alt="Emissions for the first 3 years" src="/first_years_emission.png" class="mix-w-[300px]"/>
          </picture>
        </div>
        <div class="flex flex-col w-full p-0 md:p-12 gap-y-8">
          <p class="flex flex-col font-bold">
            <span>Token issuance</span>
            <span>after three years</span>
          </p>
          <picture class="max-w-[345px]">
            <img alt="Emissions after the 3rd year" src="/3_years_emission.png" class="mix-w-[300px]"/>
          </picture>
        </div>
      </div>
      <div class="flex flex-row flex-wrap justify-center items-center w-full p-6 gap-6 ">
        <div v-for="item in chartLegend" :key="item.label" class="flex flex-inline items-center gap-1">
          <div :class="['w-[1rem] h-[1rem] rounded-full', ` ${item.color}`]"/>
          {{ item.label }}
        </div>
      </div>
    </Section>
    <footer class="footer">
      <div>
        <ULink to="/sale_disclaimer">Sale discaimer</ULink>
      </div>
    </footer>
  </UContainer>
</template>

<style scoped>
h6 {
  @apply text-gray-400;
}

.paragraphs p {
  margin-bottom: 1rem;
}

footer {
  @apply flex flex-col items-center justify-center w-full py-10;
}
</style>